### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by youngchan01** [VazkiiMods/Morph-o-Tool#66]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/13/21 4:05 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.nbt.StringNBT cannot be cast to net.minecraft.nbt.CompoundNBT
	at vazkii.morphtool.MorphingHandler.makeMorphedStack(MorphingHandler.java:160) ~[morphtool:1.4-27] {re:classloading}
	at vazkii.morphtool.MorphingHandler.getShiftStackForMod(MorphingHandler.java:122) ~[morphtool:1.4-27] {re:classloading}
	at vazkii.morphtool.ClientHandler.onTick(ClientHandler.java:45) ~[morphtool:1.4-27] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_596_ClientHandler_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1542) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[GuraF3610.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vazkii.morphtool.MorphingHandler.makeMorphedStack(MorphingHandler.java:160) ~[morphtool:1.4-27] {re:classloading}
	at vazkii.morphtool.MorphingHandler.getShiftStackForMod(MorphingHandler.java:122) ~[morphtool:1.4-27] {re:classloading}
	at vazkii.morphtool.ClientHandler.onTick(ClientHandler.java:45) ~[morphtool:1.4-27] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_596_ClientHandler_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) ~[forge:?] {re:classloading,re:mixin}
-- Affected level --
Details:
	All players: 1 total;
	Chunk stats: Client Chunk Cache: 961, 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,66,80), Chunk: (at 0,4,0 in 14,5; contains blocks 224,0,80 to 239,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 43400873 game time, 46871743 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[GuraF3610.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1207354720 bytes (1151 MB) / 3316789248 bytes (3163 MB) up to 4281597952 bytes (4083 MB)
	CPUs: 8
	JVM Flags: 6 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		forgeautofish-2.0.1-1.16.x.jar                    |AutoFish for Forge            |forgeautofish                 |2.0.1               |DONE      |NOSIGNATURE
		CustomSkinLoader_Forge-14.13-SNAPSHOT-214.jar     |CustomSkinLoader              |customskinloader              |14.13-SNAPSHOT-214  |DONE      |4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
		jei-1.16.5-7.6.4.86.jar                           |Just Enough Items             |jei                           |7.6.4.86            |DONE      |NOSIGNATURE
		fishtraps-0.1.3.jar                               |Fish Traps                    |fishtraps                     |1.16.5-0.1.3        |DONE      |NOSIGNATURE
		Uppers-0.3.2.jar                                  |Uppers                        |uppers                        |0.3.2               |DONE      |NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1b.jar                       |Create                        |create                        |mc1.16.5_v0.3.1b+143|DONE      |NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |DONE      |NOSIGNATURE
		EpicFightMod-1.16.5-3.1.3.jar                     |Epic Fight Mod                |epicfight                     |1.0                 |DONE      |NOSIGNATURE
		WeaponThrow-1.16.4-4.2.jar                        |Weapon Throw                  |weaponthrow                   |1.16.4-4.2          |DONE      |NOSIGNATURE
		Clumps-6.0.0.18.jar                               |Clumps                        |clumps                        |6.0.0.18            |DONE      |NOSIGNATURE
		XaerosWorldMap_1.13.2_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.13.2              |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		Controlling-7.0.0.14.jar                          |Controlling                   |controlling                   |7.0.0.14            |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		alexsmobs-1.9.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.9.0               |DONE      |NOSIGNATURE
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |DONE      |NOSIGNATURE
		AttachableGrinder-1.16.3-10.0.0.jar               |Attachable Grinder            |attachablegrinder             |10.0.0              |DONE      |NOSIGNATURE
		AdHooks-1.16.4-6.1.3.1-build.0039.jar             |Advanced Hook Launchers       |adhooks                       |6.1.3.1             |DONE      |NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.0.6.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.0.6      |DONE      |NOSIGNATURE
		u_team_core-1.16.5-3.2.0.194.jar                  |U Team Core                   |uteamcore                     |3.2.0.194           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		BetterHurtTimer-1.16.3-4.5.0.0.jar                |Better Hurt Timer             |betterhurttimer               |1.16.3-4.5.0.0      |DONE      |c9:84:cd:eb:27:ac:0d:ad:8c:55:6f:d6:5f:19:f2:c8:63:2a:b0:bd:3b:d0:b6:df:fd:9f:de:9f:9d:e8:7c:68
		Torched-1.16.3-10.0.0.jar                         |Torched                       |torched                       |10.0.0              |DONE      |NOSIGNATURE
		simpleplanes-1.16.4-4.1.2.jar                     |Simple Planes                 |simpleplanes                  |1.16.4-4.1.2        |DONE      |NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |NOSIGNATURE
		iChunUtil-1.16.5-10.1.0.jar                       |iChunUtil                     |ichunutil                     |10.1.0              |DONE      |NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.202.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.202           |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MmmMmmMmmMmm-1.16.5-1.1.0.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.1.0               |DONE      |NOSIGNATURE
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |DONE      |NOSIGNATURE
		supplementaries-1.16.5-0.11.0b.jar                |Supplementaries               |supplementaries               |1.16.5-0.11.0       |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.5.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		sounddeviceoptions-1.4.2.jar                      |Sound Device Options          |sounddeviceoptions            |1.4.2               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		bettermobgriefinggamerule-1.16.3-8.0.4-beta.jar   |Better mobGriefing GameRule   |bettermobgriefinggamerule     |1.16.1-8.0.2-alpha  |DONE      |NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.88.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.88           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		mana-and-artifice-1.3.0.2.jar                     |Mana and Artifice             |mana-and-artifice             |1.3.0.2             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.4-134.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.4-134    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		LetSleepingDogsLie-1.16.3-1.1.1.jar               |Let Sleeping Dogs Lie         |dogslie                       |1.1.1               |DONE      |NOSIGNATURE
		Botania-1.16.4-414.jar                            |Botania                       |botania                       |1.16.4-414          |DONE      |NOSIGNATURE
		car-1.16.4-1.0.5.jar                              |Ultimate Car Mod              |car                           |1.16.4-1.0.5        |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.0      |DONE      |NOSIGNATURE
		tetra-1.16.5-3.8.0.jar                            |Tetra                         |tetra                         |3.8.0               |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.8.3.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.3        |DONE      |NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.6.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.6.0              |DONE      |NOSIGNATURE
		FastWorkbench-1.16.4-4.5.1.jar                    |FastWorkbench                 |fastbench                     |4.5.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		AkashicTome-1.4-16.jar                            |Akashic Tome                  |akashictome                   |1.4-16              |DONE      |NOSIGNATURE
		Quark-r2.4-310.jar                                |Quark                         |quark                         |r2.4-310            |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		Clef-1.16.5-10.0.2.jar                            |Clef                          |clef                          |10.0.2              |DONE      |NOSIGNATURE
		buildersaddition-1.16.5-20210407a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210407a    |DONE      |NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |DONE      |NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |DONE      |NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		cc-tweaked-1.16.4-1.95.3.jar                      |CC: Tweaked                   |computercraft                 |1.95.3              |DONE      |NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.16.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.16       |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1b.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1b          |DONE      |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Morph-o-Tool-1.4-27.jar                           |Morph-o-Tool                  |morphtool                     |1.4-27              |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.19.jar                  |GeckoLib                      |geckolib3                     |3.0.19              |DONE      |NOSIGNATURE
		ars_nouveau-1.16.4-1.12.5.jar                     |Ars Nouveau                   |ars_nouveau                   |1.12.5              |DONE      |NOSIGNATURE
		tomeofblood-1.16.4-1.0.5.jar                      |Tome of Blood                 |tomeofblood                   |1.16.4-1.0.5        |DONE      |NOSIGNATURE
	Crash Report UUID: 6feb3fe0-f522-46cc-9f74-6e21a558faf0
	Patchouli open book context: n/a
	Launched Version: GuraF3610
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 4
	Antialiasing: 4
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.92
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by youngchan01** [comment]
The problem seem to occur when morph-o-tool tries to change into the create wrench

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please reopen the issue
