### ISSUE TITLE
[1.18.1] Mod broken - java.lang.NoSuchMethodException: vazkii.morphtool.network.MessageMorphTool

### ISSUE THREAD

**Issue by C0rn3j** [VazkiiMods/Morph-o-Tool#72]
```php
forge-1.18.1-39.0.75
Morph-o-Tool-1.5-30.jar
```
This happens when I switch the tool with SHIFT+scroll wheel, the server denies the action, making the mod not work as client thinks I have the tool I changed to, but server thinks I have plain morph-o-tool.

"full" trace:

```php
[18:56:22] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: java.lang.NoSuchMethodException: vazkii.morphtool.network.MessageMorphTool.<init>()
        at vazkii.arl.network.NetworkHandler.lambda$register$1(NetworkHandler.java:55) ~[AutoRegLib-1.7-53.jar%2341!/:1.7-53]
        at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:82) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:89) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:89) ~[forge-1.18.1-39.0.75-universal.jar%23122!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1416) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23118!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodException: vazkii.morphtool.network.MessageMorphTool.<init>()
        at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
        at vazkii.arl.network.NetworkHandler.lambda$register$1(NetworkHandler.java:51) ~[AutoRegLib-1.7-53.jar%2341!/:1.7-53]
        ... 30 more
```

**Comment by Bimmr** [comment]
Can confirm this I'm getting this error as well:
```
Forge: 1.18.1-39.0.66
AutoRegLib-1.7-52.jar 
Morph-o-Tool-1.5-30.jar
```
